version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: todopy_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2024#admin
      POSTGRES_DB: todopy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
